### ISSUE TITLE
[FEA] Renumbering Vertices

### ISSUE THREAD

**Issue by ChuckHastings** [gpuopenanalytics/graph-research#18] opened 2019-01-03 21:37 UTC
In order to support graph creation of a distributed graph, we need some mechanism to create globally unique integral values associated with each vertex.

**Comment by BradReesWork** [comment] 2019-01-08 14:49
This is a duplicate of the work being done under RAPIDS cugraph.  Marking as duplicate and closing

**Closed** 2019-01-08 14:50 UTC
Labels: closed, duplicate, feature
